"""Constants for Airtable field IDs."""


class Fields:
    NAME = "fldIGIU3NRE3i2q23"  # str, the text that appears at the top of the embeddable collection
    DESCRIPTION = "fldctH8nCVL8TlCwn"  # str, the name of the pub. Does not support rich text
    SEARCH = "fldodXKwtX4IpbozI"  # str, the Twitter search. This consists of the PubPub url and the DOI url, separated by a comma
    URL = "fldQyfONCtBouaI65"  # str, the URL of the [publishing-tools](https://github.com/Arcadia-Science/publishing-tools) collection that will be embedded
    TWEETS = "fldsM6bubBBuhX2ia"  # long text, a comma-separated list of tweet IDs
    ID = "fldiwTo38wvAY9jXz"  # str, automatically generated by the script. Note that this is distinct from Airtable's internal record ID.
    CREATED_DATE = "fldZ9vmjnIjAnhqES"  # string (ISO 8601 formatted date), the date the collection was created
