"""Constants for Airtable field IDs. Generated via env file or GitHub repository secrets."""

from dotenv import load_dotenv
import os

load_dotenv()


class Fields:
    NAME = os.getenv("NAME")  # str, the text that appears at the top of the embeddable collection
    DESCRIPTION = os.getenv("DESCRIPTION")  # str, the name of the pub. Does not support rich text
    SEARCH = os.getenv("SEARCH")  # str, the Twitter search. This consists of the PubPub url and the DOI url, separated by a comma
    URL = os.getenv("URL")  # str, the URL of the [publishing-tools](https://github.com/Arcadia-Science/publishing-tools) collection that will be embedded
    TWEETS = os.getenv("TWEETS")  # long text, a comma-separated list of tweet IDs
    ID = os.getenv("ID")  # str, automatically generated by the script. Note that this is distinct from Airtable's internal record ID.
    CREATED_DATE = os.getenv("CREATED_DATE")  # string (ISO 8601 formatted date), the date the collection was created
