name: Fetch quote tweets cron job

on:
  schedule:
    - cron: "0 0 * * *" # Run it every 24 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute script
        env:
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_ID: ${{ secrets.AIRTABLE_TABLE_ID }}
          AIRTABLE_FIELD_ID_COLLECTION_ID: ${{ secrets.AIRTABLE_FIELD_ID_COLLECTION_ID }}
          AIRTABLE_FIELD_ID_DESCRIPTION: ${{ secrets.AIRTABLE_FIELD_ID_DESCRIPTION }}
          AIRTABLE_FIELD_ID_TWEETS: ${{ secrets.AIRTABLE_FIELD_ID_TWEETS }}
          AIRTABLE_FIELD_ID_CREATED_DATE: ${{ secrets.AIRTABLE_FIELD_ID_CREATED_DATE }}
        run: python src/fetch_quote_tweets.py
